//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HJLaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_trs_pembelian
    {
        public int id_detail_transaksi_pembelian { get; set; }
        public int id_pembelian { get; set; }
        public int id_barang { get; set; }
        public int qty { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual ms_barang ms_barang { get; set; }
        public virtual trs_pembelian trs_pembelian { get; set; }
    }
}
