//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HJLaundry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class laundryEntities : DbContext
    {
        public laundryEntities()
            : base("name=laundryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detail_trs_pembelian> detail_trs_pembelian { get; set; }
        public virtual DbSet<jenis_pembayaran> jenis_pembayaran { get; set; }
        public virtual DbSet<ms_barang> ms_barang { get; set; }
        public virtual DbSet<ms_customer> ms_customer { get; set; }
        public virtual DbSet<ms_jabatan> ms_jabatan { get; set; }
        public virtual DbSet<ms_paket> ms_paket { get; set; }
        public virtual DbSet<ms_pegawai> ms_pegawai { get; set; }
        public virtual DbSet<ms_supplier> ms_supplier { get; set; }
        public virtual DbSet<trs_member> trs_member { get; set; }
        public virtual DbSet<trs_pembelian> trs_pembelian { get; set; }
        public virtual DbSet<trs_penerimaan> trs_penerimaan { get; set; }
    }
}
