//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HJLaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_pegawai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ms_pegawai()
        {
            this.trs_pembelian = new HashSet<trs_pembelian>();
        }
    
        public int id_pegawai { get; set; }
        public string nama_pegawai { get; set; }
        public System.DateTime tgl_lahir { get; set; }
        public string jenis_kelamin { get; set; }
        public string telp_pegawai { get; set; }
        public string alamat_pegawai { get; set; }
        public int id_jabatan { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int status_pgw { get; set; }
    
        public virtual ms_jabatan ms_jabatan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trs_pembelian> trs_pembelian { get; set; }
    }
}
