//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HJLaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trs_penerimaan
    {
        public int id_penerimaan { get; set; }
        public int id_customer { get; set; }
        public System.DateTime tgl_penerimaan { get; set; }
        public int id_jenis_pembayaran { get; set; }
        public int id_paket { get; set; }
        public int berat { get; set; }
        public int total_harga { get; set; }
    
        public virtual jenis_pembayaran jenis_pembayaran { get; set; }
        public virtual ms_customer ms_customer { get; set; }
        public virtual ms_paket ms_paket { get; set; }
    }
}
