//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HJLaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trs_member
    {
        public int id_trsmember { get; set; }
        public System.DateTime tgl_trsmember { get; set; }
        public string id_customer { get; set; }
        public string nama_customer { get; set; }
        public string telp_customer { get; set; }
        public string alamat_customer { get; set; }
    }
}
