//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HJLaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trs_pembelian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trs_pembelian()
        {
            this.detail_trs_pembelian = new HashSet<detail_trs_pembelian>();
        }
    
        public int id_pembelian { get; set; }
        public int id_pegawai { get; set; }
        public int id_supplier { get; set; }
        public decimal total { get; set; }
        public System.DateTime tgl_pembelian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail_trs_pembelian> detail_trs_pembelian { get; set; }
        public virtual ms_pegawai ms_pegawai { get; set; }
        public virtual ms_supplier ms_supplier { get; set; }
    }
}
